defaults:
    - override hydra/launcher: submitit_local

# loca
loca_phase: 1
loca_terminate_reach: 0
loca_one_way_wall_radius: 0.1
loca_render_size: [64, 64]
loca_dmc_camera: -1
loca_action_repeat: 2

# environment
task: dog-run
obs: state
sensor_noise: 0.0
pomdp_type: None
flicker_prob: 0.2
random_noise_sigma: 0.1
random_sensor_missing_prob: 0.1
flickering_sigma: 0.1
# robosuite specific
rs_env_name: PickPlaceSingle
rs_robots: IIWA
rs_controller: JOINT_TORQUE
rs_max_episode_steps: 200

# evaluation
checkpoint: ???
id: ???
eval_episodes: 10
eval_freq: 5000
use_tensorboard: True

# training
freeze_pi: false
steps: 10_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
burn_in: 10
enc_lr_scale: 0.3
grad_clip_norm: 1000
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: ???

# planning
random_policy: false # use this to isolate world model training
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
#horizon: 10
# TODO: use config for these
#num_samples: 64
#num_elites: 8
#num_pi_trajs: 6
horizon: 10
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
rnn_type: cfc
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
hidden_dim: 512
backbone_units: 256
backbone_layers: 1
backbone_dropout: 0.1
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8
learned_init_h: false
warmup_h: false

# logging
wandb_project: ltc-tdmpc2
wandb_entity: mihaistanusoiu-tu-wien
wandb_group: ???
wandb_silent: false
enable_wandb: true
save_csv: true

# misc
save_video: true
save_agent: true
save_buffer: false
load_buffer: false
override: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???

# speedups
compile: True